name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang-version: ['1.20', '1.21', '1.22']

    steps:
    - name: Set up Go ${{ matrix.golang-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.golang-version }}

    - name: Check out code
      uses: actions/checkout@v4
    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y upx 
    - name: Get dependencies
      run: |
        go mod download

    - name: Run tests and check coverage
      run: |
        ./coverage.sh
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: '3.11'
      - name: Validate metadata
        run: |
          pip install -U solar-registry
          solar-registry validate .